name: Build
on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Geocoder
        id: geocoder-cache
        uses: actions/cache@v1
        with:
          path: .geocoder-cache
          key: ${{ runner.os }}-geocoder-cache
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        env:
          BASE_DIR: '/'
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          npm run build
