name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Geocoder
        id: geocoder-cache
        uses: actions/cache@v1
        with:
          path: .geocoder-cache-zip
          key: ${{ runner.os }}-geocoder-cache
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        env:
          BASE_DIR: '/'
          GOOGLE_GEOCODING_API_KEY: ${{ secrets.GOOGLE_GEOCODING_API_KEY }}
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
